server:
  port: 9014
spring:
  application:
    name: tensquare-crawler #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tensquare_article?characterEncoding=UTF8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
redis:
  host: 127.0.0.1
ai:
  dataDir: F:\workspace\sk\sz42\ai\crawler
